/*
 * XenForo comments_simple.min.js
 * Copyright 2010-2017 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(b,d,c){b instanceof String&&(b=String(b));for(var e=b.length,a=0;a<e;a++){var f=b[a];if(d.call(c,f,a,b))return{i:a,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,d,c){b!=Array.prototype&&b!=Object.prototype&&(b[d]=c.value)};
$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(b,d,c,e){if(d){c=$jscomp.global;b=b.split(".");for(e=0;e<b.length-1;e++){var a=b[e];a in c||(c[a]={});c=c[a]}b=b[b.length-1];e=c[b];d=d(e);d!=e&&null!=d&&$jscomp.defineProperty(c,b,{configurable:!0,writable:!0,value:d})}};
$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6","es3");
!function(b,d,c,e){XenForo.CommentLoader=function(a){this.__construct(a)};XenForo.CommentLoader.prototype={__construct:function(a){this.$link=a;a.click(b.context(this,"click"))},click:function(a){var c=this.$link.data("loadparams");"object"!=typeof c&&(c={});a.preventDefault();XenForo.ajax(this.$link.attr("href"),c,b.context(this,"loadSuccess"),{type:"GET"})},loadSuccess:function(a){var c=this.$link.data("replace"),d;if(XenForo.hasResponseError(a))return!1;var e=c?b(c):this.$link.parent();a.comments&&
a.comments.length?new XenForo.ExtLoader(a,function(c){for(d=0;d<a.comments.length;d++)b(a.comments[d]).xfInsert("insertBefore",e);e.xfHide()}):e.xfRemove()}};XenForo.CommentPoster=function(a){this.__construct(a)};XenForo.CommentPoster.prototype={__construct:function(a){this.$link=a;this.$commentArea=b(a.data("commentarea"));this.$commentArea.data("submiturl")?this.submitUrl=this.$commentArea.data("submiturl"):this.submitUrl=a.attr("href");a.click(b.context(this,"click"));this.$commentArea.find("input:submit, button").click(b.context(this,
"submit"))},click:function(a){a.preventDefault();this.$commentArea.xfFadeDown(XenForo.speed.fast,function(){b(this).find('textarea[name="message"]').focus()})},submit:function(a){a.preventDefault();a=this.$commentArea.closest("form");a.length&&(a.data("MultiSubmitDisable")||XenForo.MultiSubmitFix(a),a.data("MultiSubmitDisable")());XenForo.ajax(this.submitUrl,{message:this.$commentArea.find('textarea[name="message"]').val(),overlay:this.$commentArea.find('input[name="overlay"]').val()},b.context(this,
"submitSuccess"))},submitSuccess:function(a){var c=this.$commentArea.closest("form");c.data("MultiSubmitEnable")&&c.data("MultiSubmitEnable")();if(XenForo.hasResponseError(a))return!1;a.comment&&b(a.comment).xfInsert("insertBefore",this.$commentArea);this.$commentArea.find('textarea[name="message"]').val("")}};XenForo.register("a.CommentLoader","XenForo.CommentLoader");XenForo.register("a.CommentPoster","XenForo.CommentPoster")}(jQuery,this,document);
