/*
 * XenForo filter_list.min.js
 * Copyright 2010-2017 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(b,d,c){b instanceof String&&(b=String(b));for(var f=b.length,a=0;a<f;a++){var e=b[a];if(d.call(c,e,a,b))return{i:a,v:e}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,d,c){b!=Array.prototype&&b!=Object.prototype&&(b[d]=c.value)};
$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(b,d,c,f){if(d){c=$jscomp.global;b=b.split(".");for(f=0;f<b.length-1;f++){var a=b[f];a in c||(c[a]={});c=c[a]}b=b[b.length-1];f=c[b];d=d(f);d!=f&&null!=d&&$jscomp.defineProperty(c,b,{configurable:!0,writable:!0,value:d})}};
$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6","es3");
!function(b,d,c,f){XenForo.FilterList=function(a){this.__construct(a)};XenForo.FilterList.prototype={__construct:function(a){this.$list=a;this.$form=this.$list.closest("form").bind("AutoValidationComplete",b.context(function(a){this.$form.find("input.Toggler").each(function(){b(this).closest("h4").toggleClass("disabled",!this.checked)})},this));this.$listCounter=this.$form.find(".FilterListCount");this.lookUpUrl=XenForo.isPositive(this.$list.data("ajaxfilter"))?this.$form.attr("action"):!1;this.registerListItems();
this.handleLast();this.activateFilterControls()&&this.filter()},activateFilterControls:function(){return this.$form.length&&(this.$filter=b('input[name="filter"]',this.$form).keyup(b.context(this,"filterKeyUp")).on("paste",b.context(this,"filterPaste")).bind("search",b.context(this,"instantSearch")).keypress(b.context(this,"filterKeyPress")),this.$prefixMatch=b('input[name="prefixmatch"]',this.$form).change(b.context(this,"filter")),this.$clearFilter=b('input[name="clearfilter"]',this.$form).click(b.context(this,
"clearFilter")),console.info("XenForo.FilterList %o",this.$filter),this.$filter.length)?this.getCookie():!1},registerListItems:function(){this.FilterListItems=[];this.$listItems=this.$list.find(".listItem");this.$listItems.each(b.context(function(a){this.FilterListItems.push(new XenForo.FilterListItem(b(this.$listItems[a])))},this));this.$groups=this.$list.find("> li:not(.listItem)")},handleLast:function(){if(d.location.hash){var a=b(d.location.hash.replace(/[^\w_#-.]/g,"").replace(".","\\."));a.hasClass("listItem")&&
(console.log("Last: %o",a),a.addClass("Last"))}},filterKeyUp:function(a){13==a.keyCode?this.instantSearch():(clearTimeout(this.timeOut),this.timeOut=setTimeout(b.context(this,"filter"),250))},filterPaste:function(a){clearTimeout(this.timeOut);this.timeOut=setTimeout(b.context(this,"filter"),250)},filterKeyPress:function(a){13==a.keyCode&&a.preventDefault()},instantSearch:function(){clearTimeout(this.timeOut);this.filter()},filter:function(a){a=this.$filter.data("XenForo.Prompt").val();var e=this.$prefixMatch.is(":checked"),
g=b.Event("XFFilter",{list:this.$list,filter:a,prefix:this.$prefixMatch.is(":checked")});this.$list.trigger(g);this.$filter.hasClass("prompt")||""===a?(this.$groups.show(),this.$listItems.show(),this.applyFilter(this.FilterListItems),this.$listCounter.text(this.$listItems.length),this.lookUpUrl&&b(".PageNav").show(),this.removeAjaxResults(),this.showHideNoResults(!1),this.deleteCookie()):(console.log("Filtering on '%s'",a),this.setCookie(),this.lookUpUrl?XenForo.ajax(this.lookUpUrl,{_filter:{value:a,
prefix:e?1:0}},b.context(this,"filterAjax"),{type:"GET"}):(a=this.applyFilter(this.FilterListItems),this.$listCounter.text(a),this.$groups.each(function(a,e){a=b(e);a.show();0==a.find("li.listItem:visible").length&&a.hide()}),this.removeAjaxResults(),this.showHideNoResults(a?!1:!0)))},removeAjaxResults:function(){this.$ajaxResults&&(this.$ajaxResults.remove(),delete this.$ajaxResults)},applyFilter:function(a){var b,g=0,c=new RegExp((this.$prefixMatch.is(":checked")?"^":"")+"("+XenForo.regexQuote(this.$filter.data("XenForo.Prompt").val())+
")","i");for(b=a.length-1;0<=b;b--)g+=a[b].filter(c);return g},showHideNoResults:function(a){var e=b("#noResults");a?(e.length||(e=b('<li id="noResults" class="listNote" style="display:none" />').text(XenForo.phrases.no_items_matched_your_filter||"No items matched your filter."),this.$list.append(e)),e.xfFadeIn(XenForo.speed.normal)):e.xfHide()},filterAjax:function(a){if(!XenForo.hasResponseError(a)){a=b("<ul />").html(b.trim(a.templateHtml)).children();this.$groups.hide();this.$listItems.hide();
this.lookUpUrl&&b(".PageNav").hide();this.removeAjaxResults();if(a.length){this.$ajaxResults=a;this.showHideNoResults(!1);this.$list.append(a);a.xfActivate();a=a.filter(".listItem").add(a.find(".listItem"));var e=[];a.each(function(a,c){e[a]=new XenForo.FilterListItem(b(c))});this.applyFilter(e);this.$listCounter.text(a.length)}else this.$listCounter.text(0),this.showHideNoResults(!0);this.handleLast()}},getCookieName:function(){var a=XenForo.canonicalizeUrl(this.$form.attr("action")),b;a=a.replace(XenForo.baseUrl(),
"");a=(b=a.match(/\?([^&=]+)(&|$)/))?b[1]:a.replace(/\?.*$/,"");return"FilterList_"+encodeURIComponent(a).replace(/[\.\+\/]|(%([0-9a-f]{2}|u\d+))/gi,"")},setCookie:function(){var a=(this.$prefixMatch.is(":checked")?1:0)+","+this.$filter.data("XenForo.Prompt").val();this.$filter.data("XenForo.Prompt").isEmpty()?this.deleteCookie():b.setCookie(this.getCookieName(),a);return a},getCookie:function(){var a=b.getCookie(this.getCookieName());a&&(this.$prefixMatch.attr("checked","1"==a.substring(0,1)?!0:
!1),this.$filter.data("XenForo.Prompt").val(a.substring(2)));return a},deleteCookie:function(){b.deleteCookie(this.getCookieName(),"")},clearFilter:function(a){this.$filter.focus();this.$filter.data("XenForo.Prompt").val("",!0);this.filter(a);return!0}};XenForo.FilterListItem=function(a){this.__construct(a)};XenForo.FilterListItem.prototype={__construct:function(a){this.$item=a;this.$textContainer=this.$item.find("h4 em");this.text=this.$textContainer.text();this.$item.find("input.Toggler").click(function(a){b(this).closest("h4").toggleClass("disabled",
!this.checked)})},filter:function(a){if(this.text.match(a))return this.$textContainer.html(XenForo.htmlspecialchars(this.text).replace(a,"<strong>$1</strong>")),this.$item.css("display","block"),1;this.$item.css("display","none");return 0}};XenForo.RadioTablets=function(a){a.children("label").each(function(){function e(c){c&&d.closest("form").submit();a.find('input:radio[name="'+d.attr("name")+'"]').each(function(){b(this).is(":checked")?b(this).closest(".radioTablet").addClass("checked"):b(this).closest(".radioTablet").removeClass("checked")})}
var c=b(this),d=c.find("input:radio");c.addClass("radioTablet");d.hide().change(e);e()})};XenForo.Sortable=function(a){var c=a.data("connect-with"),d=a.closest(".FilterList"),f=d.data("sort-url");f?a.sortable({items:"li.listItem",connectWith:c,forcePlaceholderSize:!0}).bind("sortupdate",function(a){var e=[];d.find("[data-item-id]").each(function(a){var c=b(this),d=c.data("item-id");c=c.parent().data("parent-id");e[a]=void 0!==c?[d,c]:d});d.find(c).each(function(a,c){a=b(c);0==a.find("li.listItem").length?
a.find("li.noResults").show():a.find("li.noResults").hide()});d.data("sort-timer")&&clearTimeout(d.data("sort-timer"));d.data("sort-timer",setTimeout(function(){XenForo.ajax(f,{order:e},function(a){console.info("ajax request complete")})},100))}):console.log("No FilterList or data-sort-url for sortable.")};XenForo.register(".FilterList","XenForo.FilterList");XenForo.register(".RadioTablets","XenForo.RadioTablets");XenForo.register(".Sortable","XenForo.Sortable")}(jQuery,this,document);
