/*
 * XenForo quick_reply_profile.min.js
 * Copyright 2010-2017 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,e,c){a instanceof String&&(a=String(a));for(var d=a.length,b=0;b<d;b++){var f=a[b];if(e.call(c,f,b,a))return{i:b,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,c){a!=Array.prototype&&a!=Object.prototype&&(a[e]=c.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,e,c,d){if(e){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var b=a[d];b in c||(c[b]={});c=c[b]}a=a[a.length-1];d=c[a];e=e(d);e!=d&&null!=e&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:e})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");
!function(a,e,c,d){XenForo.ProfilePoster=function(a){this.__construct(a)};XenForo.ProfilePoster.prototype={__construct:function(b){this.$form=b.bind({AutoValidationBeforeSubmit:a.context(this,"beforeSubmit"),AutoValidationComplete:a.context(this,"formValidated")});XenForo.isPositive(b.data("hide-submit"))&&(b.find(".submitUnit").hide(),b.find(".StatusEditor").focus(function(a){b.find(".submitUnit").show()}));this.listTarget=b.data("target")||"#ProfilePostList";this.submitEnableCallback=XenForo.MultiSubmitFix(this.$form)},
beforeSubmit:function(a){},formValidated:function(b){b.ajaxData._redirectTarget&&(e.location=b.ajaxData._redirectTarget);this.submitEnableCallback&&this.submitEnableCallback();this.$form.find("input:submit").blur();b.ajaxData.statusHtml&&a("#UserStatus").html(b.ajaxData.statusHtml).xfActivate();if(XenForo.hasTemplateHtml(b.ajaxData)){var c=this.listTarget;new XenForo.ExtLoader(b.ajaxData,function(){a("#NoProfilePosts").remove();a(b.ajaxData.templateHtml).xfInsert("prependTo",c)})}var d;(d=this.$form.find('textarea[name="message"]').val("").trigger("XFRecalculate").blur().data("XenForo.StatusEditor"))&&
d.update();return!1}};XenForo.register("#ProfilePoster","XenForo.ProfilePoster")}(jQuery,this,document);
