/*
 * XenForo smiley_editor.min.js
 * Copyright 2010-2017 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(b,d,c){b instanceof String&&(b=String(b));for(var e=b.length,a=0;a<e;a++){var f=b[a];if(d.call(c,f,a,b))return{i:a,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,d,c){b!=Array.prototype&&b!=Object.prototype&&(b[d]=c.value)};
$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(b,d,c,e){if(d){c=$jscomp.global;b=b.split(".");for(e=0;e<b.length-1;e++){var a=b[e];a in c||(c[a]={});c=c[a]}b=b[b.length-1];e=c[b];d=d(e);d!=e&&null!=d&&$jscomp.defineProperty(c,b,{configurable:!0,writable:!0,value:d})}};
$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6","es3");
!function(b,d,c,e){XenForo.SmileyEditor=function(a){var f=b(a.data("smiley-output"));a.find('input[name="image_url"]');var c=a.find('input[name="sprite_mode"]'),d=a.find('input[name="sprite_params[w]"]'),e=a.find('input[name="sprite_params[h]"]'),g=a.find('input[name="sprite_params[x]"]'),h=a.find('input[name="sprite_params[y]"]');f.length?a.find("input").not("input[type=button]").not("input[type=submit]").bind("change",function(b){b=a.find("#ctrl_image_url");c.is(":checked")?f.attr("src","styles/default/xenforo/clear.png").css({width:d.val(),
height:e.val(),background:"url("+b.val()+") no-repeat "+g.val()+"px "+h.val()+"px"}):f.attr("src",b.val()).css({width:"auto",height:"auto",background:"none"})}):console.warn("Unable to locate the smiley output element as specified by data-smiley-output on the form %o",a)};XenForo.SmilieImportForm=function(a){a.find("input.Hider").change(function(a){a=b(b(this).data("target"));this.checked?a.xfFadeDown(XenForo.speed.fast):a.xfHide()});a.bind({AutoValidationBeforeSubmit:function(c){c=a.serialize();
var d=a.find("input:not(input[type=hidden]), select, textarea"),e=b('<input type="hidden" name="_xfSmilieImportData" />');d.each(function(){var a=b(this);a.data("attr-name",a.attr("name"));a.removeAttr("name")});e.val(c).appendTo(a);setTimeout(function(){d.each(function(){var a=b(this);a.attr("name",a.data("attr-name"))});e.remove()},100)},AutoValidationError:function(a){a=b(a.target);a.is(":hidden")&&a.closest(".advanced").show()}})};XenForo.register("form.SmileyEditor","XenForo.SmileyEditor");XenForo.register("#SmilieImportForm",
"XenForo.SmilieImportForm")}(jQuery,this,document);
